#!/bin/bash

MONPROG=./src/freebirds

echo DEBUT
date
rm -rf OAR.*
if [ -f $MONPROG ] ; then
    for mode in "seq" "omp" "tbb" 
    do
      for boids in 100 500 1000 2000 10000
        do
        $MONPROG --numAgents $boids --numPredators 0 --numPreys 0  --mode $mode>> boids.log
      done
    done
else
   echo "ERREUR : programme $MONPROG inexistant !!"
fi


date
echo FIN